/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import DatabaseConnection.ConnectionSetup;
/**
 *
 * @author shawn
 */
public class profilePage extends javax.swing.JFrame {

    /**
     * Creates new form profilePage
     */
    private String UID;
    public profilePage() {
        initComponents();
        setValues();
        UID=null;
    }
    
    public profilePage(String id) {
        UID=id;
        initComponents();
        setValues();
    }
    
    private void setValues()
    {
        try {
            //Connection cn=null;  // to be initialized
            Connection cn=ConnectionSetup.getConnection();  // to be initialized
            Statement st=cn.createStatement();
            String query="select * from citizen where UID='" + UID + "'";
            String temp=null;
            ResultSet rs=st.executeQuery(query);
            if(rs.next())
            {
                f_name.setText(rs.getString("F_name"));
                m_name.setText(rs.getString("M_name"));
                l_name.setText(rs.getString("L_name"));
                dob.setText(rs.getDate("DOB").toString());
                gender.setText(rs.getString("Sex"));
                cate.setText(rs.getString("Category"));
                String s_UID=""+rs.getBigDecimal("S_UID");
//                System.out.println("yeah" + s_UID);
                //s_UID==null)
                
                if(s_UID==null)
                {
                    marital_status.setText("Unmarried");
                }
                else
                {
                    marital_status.setText("Married   Spouse UID :" + s_UID);
                }
                uid.setText(UID);
                nationality.setText("INDIAN");           
            }
            query="select * from work_details where UID = '" + UID + "' AND End_date is null";
            rs=st.executeQuery(query);
            if(rs.next())
            {
                street.setText(rs.getString("T_add"));
                temp= "" +  rs.getBigDecimal("T_pin");
                pin.setText(temp);
            }
//            temp=temp.substring(0,2);
            
            
            query="select * from location where Pin = '" + temp + "'";
            rs=st.executeQuery(query);
            if(rs.next())
            {
                state.setText(rs.getString("State"));
                city.setText(rs.getString("City"));
            }
            query="select * from phone_no where UID = '" + UID + "'";
            rs=st.executeQuery(query);
            if(rs.next())
            {
                ph_no.setText("" +rs.getBigDecimal("Phone_NO"));
            }
            query="select * from id where UID = '" + UID + "'";
            rs=st.executeQuery(query);
            if(rs.next())
            {
                ration_id.setText("" +rs.getInt("RATION_ID"));
                pan_id.setText("" +rs.getString("PAN_ID"));            
            }
            rs.close();
            st.closeOnCompletion();
        } catch (SQLException ex) {
            Logger.getLogger(profilePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        f_name = new javax.swing.JLabel();
        m_name = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        cate = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        marital_status = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        street = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        pin = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        nationality = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        ph_no = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ration_id = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        pan_id = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        uid = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PROFILE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name:-");

        jLabel3.setText("First name:-");

        jLabel4.setText("Middle name:-");

        jLabel5.setText("Last name:-");

        f_name.setText("jLabel6");

        m_name.setText("jLabel7");

        l_name.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("DOB:-");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Gender:-");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Category:-");

        dob.setText("jLabel13");

        gender.setText("jLabel14");

        cate.setText("jLabel15");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Marital status:-");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Address:-");

        marital_status.setText("jLabel18");

        jLabel19.setText("Street/landmark:-");

        jLabel20.setText("City:-");

        jLabel21.setText("PIN:-");

        jLabel22.setText("State:-");

        street.setText("jLabel23");

        city.setText("jLabel24");

        pin.setText("jLabel25");

        state.setText("jLabel26");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Nationality:-");

        nationality.setText("jLabel28");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Phone No.:-");

        ph_no.setText("jLabel30");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Ration ID:-");

        ration_id.setText("jLabel32");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("PAN ID:-");

        pan_id.setText("jLabel34");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("UID:-");

        uid.setText("jLabel36");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(dob)
                    .addComponent(gender))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f_name)
                    .addComponent(m_name)
                    .addComponent(l_name))
                .addGap(99, 99, 99)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addGap(47, 47, 47)
                .addComponent(cate))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(marital_status))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addGap(55, 55, 55)
                .addComponent(jLabel19)
                .addGap(62, 62, 62)
                .addComponent(street))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel20)
                .addGap(120, 120, 120)
                .addComponent(city))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel21)
                .addGap(120, 120, 120)
                .addComponent(pin))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel22)
                .addGap(111, 111, 111)
                .addComponent(state))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel35)
                .addGap(88, 88, 88)
                .addComponent(uid))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel27)
                .addGap(41, 41, 41)
                .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel29)
                .addGap(43, 43, 43)
                .addComponent(ph_no))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel31)
                .addGap(49, 49, 49)
                .addComponent(ration_id))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel33)
                .addGap(64, 64, 64)
                .addComponent(pan_id))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(dob)
                        .addGap(21, 21, 21)
                        .addComponent(gender))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(f_name)
                        .addGap(11, 11, 11)
                        .addComponent(m_name)
                        .addGap(11, 11, 11)
                        .addComponent(l_name))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cate)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(marital_status)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(street))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(city))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(pin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(state))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(uid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nationality)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ph_no)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ration_id)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(pan_id))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profilePage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cate;
    private javax.swing.JLabel city;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel f_name;
    private javax.swing.JLabel gender;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel m_name;
    private javax.swing.JLabel marital_status;
    private javax.swing.JLabel nationality;
    private javax.swing.JLabel pan_id;
    private javax.swing.JLabel ph_no;
    private javax.swing.JLabel pin;
    private javax.swing.JLabel ration_id;
    private javax.swing.JLabel state;
    private javax.swing.JLabel street;
    private javax.swing.JLabel uid;
    // End of variables declaration//GEN-END:variables
}
