/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import DatabaseConnection.ConnectionSetup;
import java.sql.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author shawn
 */
public class selectWorkDetails extends javax.swing.JFrame {

    /**
     * Creates new form selectWorkDetails
     */
    String select;
    String query;
    String table;
    String where;
    DefaultComboBoxModel model1=new DefaultComboBoxModel();
    
    DefaultComboBoxModel yearmodel1=new DefaultComboBoxModel();
    
    DefaultComboBoxModel daymodel1=new DefaultComboBoxModel();
    
    DefaultComboBoxModel daymodel2=new DefaultComboBoxModel();
    
    DefaultListModel model=new DefaultListModel();
    
    
    
    public selectWorkDetails() {
        select=new String("");
        query=new String("");
        table=new String("");
        where=new String("");
        initComponents();
        fillStatus();
        fillYear();
//        fillDate();
//        jRadioButton1.setSelected(true);
    }
    
    final void fillStatus()
    {
        model1.addElement("none");
        String q="select distinct status_name from status";
        Connection cn=ConnectionSetup.getConnection();
        
        Statement st=ConnectionSetup.getStatement(cn);
        try {
            ResultSet rs=st.executeQuery(q);
            
            
            while(rs.next())
            {
                model1.addElement(rs.getString("Status_name"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(selectWorkDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    final void fillYear()
    {
        Date d = new Date();
        int j;
        for(int i=0;i<=d.getYear();i++ )
        {
            j=i+1900;
            yearmodel1.addElement(""+j);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SELECT WORK DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(212, 11, 213, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Sector:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(65, 52, 56, 17);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Private");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(182, 51, 59, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Public");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(283, 51, 53, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Status:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(65, 92, 56, 17);

        jComboBox1.setModel(model1);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(185, 92, 151, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Start date:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(65, 130, 81, 17);

        jLabel5.setText("Year");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(185, 133, 22, 14);

        jComboBox2.setModel(yearmodel1);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(225, 130, 28, 20);

        jLabel6.setText("Month");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(342, 133, 30, 14);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(402, 130, 49, 20);

        jLabel7.setText("Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(508, 133, 23, 14);

        jComboBox4.setModel(daymodel1);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(549, 130, 28, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("End Date:-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(65, 178, 74, 17);

        jLabel9.setText("Year");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(185, 181, 22, 14);

        jComboBox5.setModel(yearmodel1);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(225, 178, 28, 20);

        jLabel10.setText("Month");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(342, 181, 30, 14);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(402, 178, 49, 20);

        jLabel11.setText("Date");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(508, 181, 23, 14);

        jComboBox7.setModel(daymodel2);
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(549, 178, 28, 20);

        jButton1.setText("Execute");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(506, 241, 71, 23);

        jList1.setModel(model);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(65, 292, 512, 130);

        jButton2.setText("Store this result for more queries");
        getContentPane().add(jButton2);
        jButton2.setBounds(65, 440, 191, 23);

        jButton3.setText("Proceed for new query");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(434, 440, 143, 23);

        jPanel1.setBackground(new java.awt.Color(253, 241, 224));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 680, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        //select sector
        if(jRadioButton1.isSelected())
        {
            where+="work_details.sector=1";
            table="work_details";
        }
        if(jRadioButton2.isSelected())
        {
            where+="work_details.sector=2";
            table="work_details";
        }
        //select start date
        if(!jComboBox2.getSelectedItem().equals("none"))
        {
            table="work_details";
            String date=new String("");
            date+=jComboBox2.getSelectedItem()+"-";
            if(jComboBox3.getSelectedItem().equals("none"))
            {
                date+="01"+"-";
            }
            else
            {
                date+=jComboBox3.getSelectedItem()+"-";
            }
            if(jComboBox4.getSelectedItem().equals("none"))
            {
                date+="01";
            }
            else
            {
                date+=jComboBox4.getSelectedItem();
            }
            if(!where.equals(""))
            {
                where+=" AND ";
            }
            where+="start_date='"+date+"'";
        }
        //select end date
        if(!jComboBox5.getSelectedItem().equals("none"))
        {
            table="work_details";
            String date=new String("");
            date+=jComboBox5.getSelectedItem()+"-";
            if(jComboBox6.getSelectedItem().equals("none"))
            {
                date+="01"+"-";
            }
            else
            {
                date+=jComboBox6.getSelectedItem()+"-";
            }
            if(jComboBox7.getSelectedItem().equals("none"))
            {
                date+="01";
            }
            else
            {
                date+=jComboBox7.getSelectedItem();
            }
            if(!where.equals(""))
            {
                where+=" AND ";
            }
            where+="end_date='"+date+"'";
        }
        //select status
        if(!jComboBox1.getSelectedItem().equals("none"))
        {
            table="work_details join status on status.status_ID=work_details.status";
            if(!where.equals(""))
            {
                where+=" AND ";
            }
            where+="work_details.status='"+jComboBox1.getSelectedItem()+"'";
        }
        query="select work_details.UID from "+table+" where "+where+" ;";
        System.out.println(query);
        
        Connection cn=ConnectionSetup.getConnection();
        Statement st=ConnectionSetup.getStatement(cn);
        
        ResultSet rs;
        try {
            rs = st.executeQuery(query);
            while(rs.next())
        {
            model.addElement("" + rs.getBigDecimal("UID"));
            
        }
        } catch (SQLException ex) {
            Logger.getLogger(selectWorkDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String s;
        if(jComboBox2.getSelectedItem()==null)
        {
            s="none";
        }
        else
        {
            s=jComboBox2.getSelectedItem().toString();
        }
       if(s.equals("none"))
       {
           jComboBox3.setEnabled(false);
           jComboBox4.setEnabled(false);
       }
       else
       {
           jComboBox3.setEnabled(true);
           String a;
           if(jComboBox3.getSelectedItem()==null)
           {
               a="none";
           }
           else
           {
               a=jComboBox3.getSelectedItem().toString();
           }
           if(!a.equals("none"))
            jComboBox4.setEnabled(true);
           else
            jComboBox4.setEnabled(false);   
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        daymodel1.removeAllElements();
        String s=String.valueOf(jComboBox3.getSelectedItem());
        int k=0;
        if(s.equals("none"))
        {
            jComboBox4.setEnabled(false);
        }
        else
        {
            if(s.equals("1") || s.equals("3") ||s.equals("5") ||s.equals("7") ||s.equals("8") || s.equals("10") ||s.equals("12") )
            {
                k=31;
            }
            else if(s.equals("2"))
            {
                k=28;
            }
            else
            {
                k=30;
            }
        }
        for(int i=1;i<=k;i++)
        {
            daymodel1.addElement(""+i);
        }
        
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
                String s;
        if(jComboBox5.getSelectedItem()==null)
        {
            s="none";
        }
        else
        {
            s=jComboBox5.getSelectedItem().toString();
        }
       if(s.equals("none"))
       {
           jComboBox6.setEnabled(false);
           jComboBox7.setEnabled(false);
       }
       else
       {
           jComboBox6.setEnabled(true);
           String a;
           if(jComboBox6.getSelectedItem()==null)
           {
               a="none";
           }
           else
           {
               a=jComboBox6.getSelectedItem().toString();
           }
           if(!a.equals("none"))
            jComboBox7.setEnabled(true);
           else
            jComboBox7.setEnabled(false);   
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        daymodel2.removeAllElements();
        String s=String.valueOf(jComboBox6.getSelectedItem());
        int k=0;
        if(s.equals("none"))
        {
            jComboBox7.setEnabled(false);
        }
        else
        {
            if(s.equals("1") || s.equals("3") ||s.equals("5") ||s.equals("7") ||s.equals("8") || s.equals("10") ||s.equals("12") )
            {
                k=31;
            }
            else if(s.equals("2"))
            {
                k=28;
            }
            else
            {
                k=30;
            }
        }
        for(int i=1;i<=k;i++)
        {
            daymodel2.addElement(""+i);
        }
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectWorkDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectWorkDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectWorkDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectWorkDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectWorkDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
