/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import DatabaseConnection.ConnectionSetup;
import com.sun.xml.internal.ws.util.StringUtils;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.util.*;

/**
 *
 * @author shawn
 */
public class selectSalary extends javax.swing.JFrame implements ListSelectionListener{
    
    Connection cn=null;

    /**
     * Creates new form selectSalary
     */
    public selectSalary() {
        cn=ConnectionSetup.getConnection();
        initComponents();
        rangeSelect.setSelected(true);
        result_lst.setModel(model);
        result_lst.addListSelectionListener(this);
    }
    
    DefaultListModel model = new DefaultListModel();
    
    
    
//    public DefaultModel getModel()
  //  {
        
    //}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rangeSelect = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Min = new javax.swing.JTextField();
        Max = new javax.swing.JTextField();
        include_radio = new javax.swing.JRadioButton();
        bpl_radio = new javax.swing.JRadioButton();
        execute = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result_lst = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(null);

        buttonGroup1.add(rangeSelect);
        rangeSelect.setText("SELECT SALARY RANGE");
        rangeSelect.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rangeSelectStateChanged(evt);
            }
        });
        getContentPane().add(rangeSelect);
        rangeSelect.setBounds(159, 52, 139, 23);

        jLabel4.setText("MIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(325, 82, 19, 14);

        jLabel5.setText("MAX");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(324, 113, 21, 14);
        getContentPane().add(Min);
        Min.setBounds(363, 79, 136, 20);

        Max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxActionPerformed(evt);
            }
        });
        getContentPane().add(Max);
        Max.setBounds(363, 110, 136, 20);

        include_radio.setText("include");
        getContentPane().add(include_radio);
        include_radio.setBounds(546, 90, 59, 23);

        buttonGroup1.add(bpl_radio);
        bpl_radio.setText("BPL");
        getContentPane().add(bpl_radio);
        bpl_radio.setBounds(159, 159, 43, 23);

        execute.setText("EXECUTE");
        execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeActionPerformed(evt);
            }
        });
        getContentPane().add(execute);
        execute.setBounds(343, 199, 156, 23);

        result_lst.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(result_lst);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 318, 1024, 244);

        jButton2.setText("Store the result");
        getContentPane().add(jButton2);
        jButton2.setBounds(69, 573, 245, 34);

        jButton3.setText("Proceed for further filters");
        getContentPane().add(jButton3);
        jButton3.setBounds(403, 573, 245, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELECT SALARY        ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 20, 1004, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(19, 296, 130, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FIRST NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(159, 295, 124, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MIDDLE NAME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(317, 295, 155, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LAST NAME");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(503, 295, 161, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SEX");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(682, 295, 166, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SALARY");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(866, 295, 148, 17);

        jButton1.setText("Thanks! Start a new Query");
        getContentPane().add(jButton1);
        jButton1.setBounds(737, 573, 245, 34);

        jPanel1.setBackground(new java.awt.Color(253, 241, 224));
        jPanel1.setMinimumSize(new java.awt.Dimension(1021, 611));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -30, 1040, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeActionPerformed
        try {
          //   TODO add your handling code here:
   //         int min=Integer.parseInt(Min.getText());
      //      int max=Integer.parseInt(Max.getText());
            int k;
            String temp;
            model.removeAllElements();
            if(rangeSelect.isSelected())
            {
            
               String min=(Min.getText().trim());
               String max=(Max.getText().trim());
               ResultSet rs=null;
               String query;
               if(include_radio.isSelected())
               {    
                    query="select citizen.UID,citizen.F_name,M_name,L_name,Sex,work_details.salary from citizen,work_details where citizen.UID=work_details.UID AND work_details.end_date is null AND salary > '" + min  + "' AND salary < '" + max + "'";
               }
               else
               {
                    query="select citizen.UID,citizen.F_name,M_name,L_name,Sex,work_details.salary from citizen,work_details where citizen.UID=work_details.UID AND work_details.end_date is null AND ( salary < '" + min  + "' OR salary > '" + max + "')";
               }
//               String query="select citizen.UID,citizen.F_name,work_details.salary from citizen,work_details where citizen.UID=work_details.UID AND salary > '100' AND salary < '500'";
//            System.out.println(query);
            Statement st=ConnectionSetup.getStatement(cn);
            
            try {
                
            if(SelectPage.state==1)
            {
                String q1=SelectPage.imp;
                query=query + " UNION " + q1;
            }
            else if(SelectPage.state==2)
            {
                String q1=SelectPage.imp;
                query=query + " INTERSECT " + q1;
            }
            else if(SelectPage.state==3)
            {
                String q1=SelectPage.imp;
                query=query + " EXCEPT " + q1;
            }
                rs=st.executeQuery(query);
            } catch (SQLException ex) {
                Logger.getLogger(selectSalary.class.getName()).log(Level.SEVERE, null, ex);
            }
            while(rs.next())
            {
//                System.out.println("yeah!!");
                String uid="" +rs.getBigDecimal("uid");
                uid+="                  ";
                String f_name=rs.getString("F_name");
//                k=(60-f_name.length())/2;
                  k=(60-f_name.trim().length());
//                temp=f_name;
  //              for(int i=0;i<k;i++)
    //            {
      //              temp+=" ";
        //        }
        //        temp+=f_name;
          //      for(int i=0;i<k;i++)
     //           {
       //             temp+=" ";
         //       }
                f_name=String.format("%-"+k+"s", f_name);
                
                String m_name=rs.getString("M_name");
//                k=(60-m_name.length())/2;
                                k=(60-m_name.trim().length());
  //              temp=m_name;
    //            for(int i=0;i<k;i++)
      //          {
        //            temp+=" ";
          //      }
//                temp+=m_name;
  //              for(int i=0;i<k;i++)
    //            {
      //              temp+=" ";
        //        }
//                m_name=temp;
                m_name =String.format("%-"+k+"s",m_name);
                
                String l_name=rs.getString("L_name");
                
    //            k=(60-l_name.length())/2;
                k=(60-l_name.trim().length());
//                temp=l_name;
  //              for(int i=0;i<k;i++)
    //            {
      //              temp+=" ";
        //        }
//                temp+=l_name;
//                for(int i=0;i<k;i++)
  //              {
    ///                temp+=" ";
       //         }
                l_name=String.format("%-"+k+"s", l_name);
                
                String sex=rs.getString("Sex");
                
//                k=(60-sex.length())/2;
                  k=(60-sex.trim().length());
//                temp=sex;
  //              for(int i=0;i<k;i++)
    //            {
      //              temp+=" ";
        //        }
//                temp+=sex;
  //              for(int i=0;i<k;i++)
    //            {
      //              temp+=" ";
        //        }
                sex=String.format("%-"+k+"s",sex);
                
                
                
                
                String sal=""+rs.getInt("Salary");
//                k=(60-sal.length())/2;
                k=(60-sal.trim().length());
//                temp=sal;
  //              for(int i=0;i<k;i++)
    //            {
      //              temp+=" ";
        //        }
//                temp+=sal;
  //              for(int i=0;i<k;i++)
    //            {
      //              temp+=" ";
        //        }
                sal=String.format("%-"+k+"s",sal);
                
                model.addElement(uid+"  " + f_name + " "+ m_name+ " "+l_name+" "+sex+ " "+sal );
                
            }
            SelectPage.imp=query;
            }
            else if(bpl_radio.isSelected())
            {
             //   String query="select citizen.UID,citizen.F_name,work_details.salary from citizen,work_details where citizen.UID=work_details.UID AND work_details.end_date is null AND salary < '300000'";
                String query="select uid from BPL";
                            Statement st=ConnectionSetup.getStatement(cn);
                ResultSet rs=null;
            try {
                if(SelectPage.state==1)
            {
                String q1=SelectPage.imp;
                query=query + " UNION " + q1;
            }
            else if(SelectPage.state==2)
            {
                String q1=SelectPage.imp;
                query=query + " INTERSECT " + q1;
            }
            else if(SelectPage.state==3)
            {
                String q1=SelectPage.imp;
                query=query + " EXCEPT " + q1;
            }
                rs=st.executeQuery(query);
            } catch (SQLException ex) {
                Logger.getLogger(selectSalary.class.getName()).log(Level.SEVERE, null, ex);
            }
            while(rs.next())
            {
//                System.out.println("yeah!!");
                String a=""+rs.getBigDecimal("UID");
              String b=rs.getString("F_name");
             //   int c=rs.getInt("salary");
                
              //  result_lst.add(a+b+c);
         //       model.addElement(a + "       " + b + "        " + c);
                     model.addElement(a);
            }
            SelectPage.imp=query;
            }
            else
            {
                // dialog box saying wrong input...
               // jDialog j= 
                JOptionPane.showMessageDialog(this, "Input not selected properly.","Wrong input!!",JOptionPane.ERROR_MESSAGE);
            }
            
            
            
            
        }catch (SQLException ex) {
            Logger.getLogger(selectSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_executeActionPerformed

    private void rangeSelectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rangeSelectStateChanged
        // TODO add your handling code here:
       if(!rangeSelect.isSelected())
       {
           Min.setEnabled(false);
           Max.setEnabled(false);
           include_radio.setEnabled(false);
       }
       else
       {
           Min.setEnabled(true);
           Max.setEnabled(true);
           include_radio.setEnabled(true);
       }
        
        
    }//GEN-LAST:event_rangeSelectStateChanged

    private void MaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectSalary().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Max;
    private javax.swing.JTextField Min;
    private javax.swing.JRadioButton bpl_radio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton execute;
    private javax.swing.JRadioButton include_radio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rangeSelect;
    private javax.swing.JList result_lst;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if(e.getSource()==result_lst)
        {
            String id=result_lst.getSelectedValue().toString().trim().substring(0,12);
            System.out.println(id);
              profilePage pp=new profilePage(id.trim());
              pp.setVisible(true);
        }
 //       throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
