/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import DatabaseConnection.ConnectionSetup;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author shawn
 */
public class selectCrime extends javax.swing.JFrame {

    /**
     * Creates new form selectCrime
     */
    String select;
    String query;
    String table;
    String where;
    DefaultListModel model=new DefaultListModel();
    DefaultComboBoxModel model1=new DefaultComboBoxModel();
    
    public selectCrime() {
        select=new String("");
        query=new String("");
        table=new String("");
        where=new String("");
        initComponents();
        fillCrime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      final void fillCrime()
    {
        model1.addElement("none");
        String q="select distinct offense_type from crime_type";
        Connection cn=ConnectionSetup.getConnection();
        
        Statement st=ConnectionSetup.getStatement(cn);
        try {
            ResultSet rs=st.executeQuery(q);
            
            while(rs.next())
            {
                model1.addElement(rs.getString("offense_type"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(selectWorkDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        result_lst = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT CRIME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(78, 34, 455, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Crime type : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 163, 98, 17);

        jComboBox1.setModel(model1);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(273, 163, 171, 20);

        jButton1.setText("Execute");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(254, 217, 71, 23);

        result_lst.setModel(model);
        result_lst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                result_lstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(result_lst);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 266, 592, 130);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(131, 419, 73, 23);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(393, 419, 73, 23);

        jPanel1.setBackground(new java.awt.Color(253, 241, 224));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 610, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        model.removeAllElements();
        if(!jComboBox1.getSelectedItem().equals("None"))
        {
            table="(crime_type join criminals join crime on criminals.FIR=crime.FIR AND crime.offense=crime_type.offense_ID)";
            where="crime_type.Offense_type='"+jComboBox1.getSelectedItem()+"'";
            query="select criminals.UID from "+table+" where "+where;
        Connection cn=ConnectionSetup.getConnection();
        Statement st=ConnectionSetup.getStatement(cn);
        
        ResultSet rs;
        try {
            rs = st.executeQuery(query);
        while(rs.next())
        {
            model.addElement("" + rs.getBigDecimal("UID"));
        }
        rs.close();
        st.close();
        cn.close();
               
        } catch (SQLException ex) {
            Logger.getLogger(selectWorkDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            System.out.println(query);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void result_lstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_result_lstValueChanged
        // TODO add your handling code here:
        if(evt.getSource()==result_lst)
        {
            String id=result_lst.getSelectedValue().toString().trim().substring(0,12);
            System.out.println(id);
              profilePage pp=new profilePage(id.trim());
              pp.setVisible(true);
        }
    }//GEN-LAST:event_result_lstValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectCrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectCrime().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList result_lst;
    // End of variables declaration//GEN-END:variables
}
